package main

import (
	"bytes"
	"fmt"
	"go/format"
	"log"

	"github.com/go-gad/dekit/looker"
)

type generator struct {
	buf bytes.Buffer
}

func (g *generator) Generate(pkg *looker.Package) error {
	g.p("// Code generated by dekit. DO NOT EDIT.")

	//g.p("package %v", dstPkg.Name())

	return nil
}

// Output returns the generator's output, formatted in the standard Go style.
func (g *generator) Output() []byte {
	src, err := format.Source(g.buf.Bytes())
	if err != nil {
		log.Fatalf("Failed to format generated source code: %s\n%s", err, g.buf.String())
	}
	return src
}

func (g *generator) p(format string, args ...interface{}) {
	fmt.Fprintf(&g.buf, format+"\n", args...)
}

func (g *generator) br() {
	g.p("")
}
