// Code generated by dekit. DO NOT EDIT.
package testdata

import (
	"net/http"
)

func decodeCreateOrderReq(r *http.Request) (*CreateOrderReq, error) {
	var msg CreateOrderReq
	msg.Name = r.URL.Query().Get("name")
	return &msg, nil
}
